# Generated by Django 4.1.7 on 2023-03-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0006_auto_20230318_0309"),
    ]

    operations = [
        migrations.AddField(
            model_name="dish",
            name="picture",
            field=models.CharField(default="", max_length=500),
        ),
    ]
