# Generated by Django 4.1.7 on 2023-03-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0007_dish_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dish", name="picture", field=models.CharField(max_length=500),
        ),
    ]
