# Generated by Django 4.1.7 on 2023-03-19 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rango", "0008_alter_dish_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="password",
            field=models.CharField(default="", max_length=100),
        ),
    ]
